#!/bin/bash

FG='#dcdcdc'
# BG='#333333'
BG='#090909'

font1='Ubuntu:size=10'
# line_count=$(($(mpc playlist | wc -l)))
line_count=8

monitors=$(xrandr --listactivemonitors | head -1 | awk '{print $2}')
if [ $monitors == '1' ]
then
	screen_height=$(xrandr --listactivemonitors | head -2 | tail -1 | cut -dx -f2 | awk '{print $1+0}')

	x=0
	# y=899
	y=$(($screen_height - $line_count * 16 - 28 - 34))
else
	screen_height=$(xrandr --listactivemonitors | head -2 | tail -1 | cut -dx -f2 | awk '{print $1+0}')

	x=1920
	# y=1018
	y=$(($screen_height - $line_count * 16 - 28 - 34))
fi

playlist=$(mpc playlist | sed 's/^/   \^fn(Ionicons:size=10)^fg(#beffbe)^fg(#dcdcdc)^fn(Meslo LG S DZ:size=9) /')

sleep 1

fifo="/tmp/mpd_playlist_script.fifo"
[ ! -e $fifo ] && mkfifo $fifo
echo -e "\n$playlist" | dzen2 -m -p 10 -x $x -y $y -w "250" -bg $BG -fg $FG -l "8" -sa 'l' -ta 'c' -e 'onstart=uncollapse,scrollhome;button1=menuprint,exit;button3=exit;button4=scrollup:1;button5=scrolldown:1' -fn $font1 > $fifo &

pid=$!
echo $pid
# strace -p $pid > ~/.config/lemonbuddy/scripts/$pid.log 2>&1 &

while read line
do
	choice="$line"
done < $fifo

IFS=$'\n'
for line in $(mpc playlist | cat -n)
do
	if [ "$(echo "$choice" | cut -d ' ' -f2-)" == "$(echo "$line" | awk '{print substr($0, index($0, $2))}')" ]
	then
		mpc play $(echo "$line" | awk '{print $1}') > /dev/null 2>&1
	fi
done

