#!/bin/bash

logfile="$HOME/.cache/train_on_time.log"

trainId=17761
hour=1730
station="MACON VILLE"

wget -q -O $logfile "http://www.sncf.com/sncf/train?numeroTrain=$trainId&date=$(date +%d/%m/%Y)&heure=$hour&fromRedirect=true&companyCode=SN&equipmentType=TER"

IFS=$'\n'

get_infos() {
	line_city=$(cat -n $logfile | grep "$station" | awk '{print $1}')
	line_hour=$((line_city - $1))
	line_on_time=$((line_city + $2))
	line_delay_reason=$((line_city + $2 + 1))
	lines="${line_hour}p;${line_city}p;${line_on_time}p;${line_delay_reason}p"

	if [ -n "$line_city" ]
	then
		cat $logfile | sed -n "$lines" | sed -e 's/<[^>]*>//g' | awk '{$1=$1};1' | tr -d $'\r'
	fi
}

text=($(get_infos 9 8))
[ -z "${text[3]}" ] && text=($(get_infos 7 8))

# echo "=== DEBUG ==="
# for i in ${text[@]}
# do
# 	echo $i
# done
# echo "============="

if [ -n "${text[2]}" ] && [ "$(date +%u)" -le 5 -a "$(date +%H)" -ge 16 -a "$(date +%H)" -le 18 -a "$(date +%M)" -le 30 ]
then
	echo -n "${text[1]}" | sed 's/[^ ]\+/\L\u&/g'
	echo -n " at ${text[0]}: " | tr '[:upper:]' '[:lower:]'
	echo "${text[2]}" | sed 's/[^ ]\+/\L\u&/g'
	# echo -n "${text[1]} at ${text[0]}: ${text[2]}"

	# if [ "${text[2]}" != "On time" ]
	# then
	# 	echo " ${text[3]}" | tr '[:upper:]' '[:lower:]' | tr -d ':'
	# else
	# 	echo
	# fi

	if [ "$1" == "--notify" ] || [ "$(date +%H)" -ge "17" -a "$(date +%M)" -ge "30" -a "${text[2]}" != "On time" ]
	then
		notify-send -u critical "SNCF" "Train $(echo ${text[2]} | tr '[:upper:]' '[:lower:]')!\nReason:$(echo -n ${text[3]} | cut -d':' -f2-)"
	fi
# else
# 	echo "N/A"
fi

