#!/bin/env python3
# encoding: utf-8

from piecash import open_book
from os.path import expanduser

with open_book(expanduser("~") + "/Dropbox/Comptes/MesComptes.gnucash", open_if_lock=True) as book:
    for acc in book.accounts:
        if acc.name == "Compte chèques":
            print(acc.get_balance(), "€", sep=' ')
