#!/usr/bin/env python3

from bs4 import BeautifulSoup
import calendar
import os
import requests
import time

# def getYoutubeTitle(videoID):
#     url = 'http://youtube.com?' + videoID
#     r = requests.get(url)
#     html_content = r.text
#     soup = BeautifulSoup(html_content, 'lxml')
#     return soup.title.string
#
# videoID = os.popen("qdbus org.mpris.MediaPlayer2.smplayer /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Metadata | grep title | cut -d: -f3- | sed 's/^ *//g'").read()
# title = getYoutubeTitle(videoID)

# title = os.popen("qdbus org.mpris.MediaPlayer2.vlc /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Metadata | grep title | cut -d: -f3- | sed 's/^ *//g'").read()
title = os.popen("qdbus org.mpris.MediaPlayer2.smplayer /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Metadata | grep title | cut -d: -f3- | sed 's/^ *//g'").read()[:-1]

if len(title) == 0:
    title = "none"

maxWidth = 30
delay = 5

if len(title) >= maxWidth:
    state = calendar.timegm(time.gmtime()) * 2 % (len(title) - maxWidth + delay * 2 + 2)
    if state < delay * 2:
        print("[", title[0:maxWidth], "]", sep='')
    elif state > len(title) - maxWidth + delay * 2 - 1:
        print("[", title[-maxWidth - 1:-1], "]", sep='')
    else:
        state -= delay * 2
        print("[", title[state:state + maxWidth], "]", sep='')
else:
    print("[", title, "]", sep='')

