#!/bin/bash

FG='#dcdcdc'
# BG='#333333'
BG='#090909'

font1="Monospace:size=10"

# monitors=$(xrandr --listactivemonitors | head -1 | awk '{print $2}')
# if [ $monitors == '1' ]
# then
	x=843
	y=28
# else
# 	x=2763
# 	y=28
# fi

TODAY=$(expr `date +'%d'` + 0)
MONTH=`date +'%m'`
YEAR=`date +'%Y'`

next_month=`date --date='+1 month' +'%m %Y'`
prev_month=`date --date='-1 month' +'%m %Y'`

day_year=$(date +'%j')
week_year=$(date +'%V')

color1='#575757'
color2='#323232'
color3='#f0f0f0'
color4='#6c6c6c'
color5='#a7a7a7'

cal_p_m=`cal $prev_month | sed -re "s/^(.*[A-Za-z][A-Za-z]*.*)$/^fg($color5)^bg($color2) \1 /"`
cal_c_m=`cal | sed -re "s/^(.*[A-Za-z][A-Za-z]*.*)$/^fg($color3)^bg($color1) \1 /;
s/(^|[ ])($TODAY)($|[ ])/\1^bg($color1)^fg($color2)\2^fg($color4)^bg($color2)\3/"`
cal_n_m=`cal $next_month | sed -re "s/^(.*[A-Za-z][A-Za-z]*.*)$/^fg($color5)^bg($color2) \1 /"`

sleep 1

(
echo "
^fg(#e2abd4)^fn(Monospace:bold:size=10)Time & Date
"
echo "$cal_p_m
"
echo "$cal_c_m
"
echo "$cal_n_m
"
# current month, hilight header and today
echo "Current day of the year: $day_year"
echo "Current week of the year: $week_year"
echo ""

) | dzen2 -p 10 -x $x -y $y -w 240 -bg $BG -fg $FG -l 32 -sa c -ta c -e 'onstart=uncollapse;button1=exit;button3=exit' -fn $font1 -xs "$(bash ~/.local/bin/get-current-output | awk '{print $2}')" &

pid=$!
echo $pid
wait $pid

