#!/bin/bash

FG='#dcdcdc'
# BG='#333333'
BG='#090909'

font1='Ubuntu:pixelsize=13'
line_count=8

# monitors=$(xrandr --listactivemonitors | head -1 | awk '{print $2}')
# if [ $monitors == '1' ]
# then
	screen_height=$(xrandr --listactivemonitors | head -2 | tail -1 | cut -dx -f2 | awk '{print $1+0}')

	x=1635
	# y=899
	y=$(($screen_height - $line_count * 16 - 28 - 16))
# else
# 	screen_height=$(xrandr --listactivemonitors | head -2 | tail -1 | cut -dx -f2 | awk '{print $1+0}')
#
# 	x=3545
# 	# y=1018
# 	y=$(($screen_height - $line_count * 16 - 28 - 16))
# fi

updates=$(checkupdates | sed 's/^/   \^fn(Ionicons:size=10)^fg(#beffbe)^fg(#dcdcdc)^fn(Meslo LG S DZ:size=9) /')

echo -e "\n$updates" | dzen2 -p 10 -x $x -y $y -w "250" -bg $BG -fg $FG -l "$line_count" -sa 'l' -ta 'c' -e 'onstart=uncollapse,scrollhome;enterslave=grabkeys;leaveslave=ungrabkeys;key_Home=scrollhome;key_End=scrollend;button1=exit;button3=exit;button4=scrollup:1;button5=scrolldown:1' -fn $font1 -xs "$(bash ~/.local/bin/get-current-output | awk '{print $2}')" &

pid=$!
echo $pid
wait $pid

