#!/bin/bash

FG='#dcdcdc'
# BG='#333333'
BG='#090909'

font1="Inconsolata:pixelsize=15"
width=$((80 * 8))

# monitors=$(xrandr --listactivemonitors | head -1 | awk '{print $2}')
# if [ $monitors == '1' ]
# then
	x=$((1920 / 2 - $width / 2))
	y=28
# else
# 	x=$((1920 + 1920 / 2 - $width / 2))
# 	y=28
# fi

reminders="$(remind -c2 -b1 -m ~/.reminders)"
line_count=$(remind -c1 -b1 -m ~/.reminders | wc -l)

sleep 1

(

echo
echo "$reminders"

) | dzen2 -p 10 -x $x -y $y -w $width -bg $BG -fg $FG -l $line_count -sa c -ta c -e "onstart=uncollapse,scrollhome;enterslave=grabkeys;leaveslave=ungrabkeys;key_Home=scrollhome;key_End=scrollend;button1=exit;button3=exit;button4=scrollup:1;button5=scrolldown:1" -fn $font1 -xs "$(bash ~/.local/bin/get-current-output | awk '{print $2}')" &

pid=$!
echo $pid
wait $pid

