#!/bin/bash

bash ~/.config/polybar/kill &

if type "xrandr" > /dev/null; then
	for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
		xrandr --output $m --auto
	done

	for m in $(xrandr --query | grep " disconnected" | cut -d" " -f1); do
		xrandr --output $m --off
	done
fi

# Needed to setup my personal workspace
if [ "$1" == "workspace" ]; then
	old_output=""
	for output in eDP-1 HDMI-1; do
	# for output in eDP-1 DP-2 DP-1; do
	# for output in eDP-1 DP-1; do
	# for output in eDP1 DP2 DP1; do
		if [ -z $(xrandr --query | grep "$output connected") ]; then
			continue
		fi

		if [ -n "$old_output" ]; then
			xrandr --output $old_output --left-of $output
		else
			xrandr --output $output --auto
		fi

		old_output=$output
	done

	xrandr --output HDMI-1 --preferred --primary
fi

bash ~/.config/polybar/launch &

