#!/bin/bash

bash ~/.config/polybar/kill

echo "[*] Launched $(LANG="en_US.UTF-8" date '+%a %e %b %H:%M:%S')" >> ~/.config/polybar/top.log
echo "[*] Launched $(LANG="en_US.UTF-8" date '+%a %e %b %H:%M:%S')" >> ~/.config/polybar/bottom.log

export POLYBAR_WLO=$(cat /proc/net/wireless | perl -ne '/(\w+):/ && print $1')
export POLYBAR_ETH=$(ip -o link show | awk -F': ' '{print $2}' | grep -E "^e")

if type "xrandr" > /dev/null; then
	for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
		MONITOR=$m polybar --reload top >> ~/.config/polybar/top.log 2>&1 &

		if [ "$1" != "--only-top" ];
		then
			MONITOR=$m polybar --reload bottom >> ~/.config/polybar/bottom.log 2>&1 &
		fi
	done
else
	polybar --reload top >> ~/.config/polybar/top.log 2>&1 &

	if [ "$1" != "--only-top" ];
	then
		polybar --reload bottom >> ~/.config/polybar/bottom.log 2>&1 &
	fi
fi

