#!/bin/bash

killall -q polybar

while pgrep -x polybar > /dev/null
do
	sleep 1
done

echo "[*] Launched $(LANG="en_US.UTF-8" date '+%a %e %b %H:%M:%S')" >> ~/.config/polybar/top.log
echo "[*] Launched $(LANG="en_US.UTF-8" date '+%a %e %b %H:%M:%S')" >> ~/.config/polybar/bottom.log

if type "xrandr" > /dev/null; then
	for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
		MONITOR=$m polybar --reload top >> ~/.config/polybar/top.log 2>&1 &
		MONITOR=$m polybar --reload bottom >> ~/.config/polybar/bottom.log 2>&1 &
	done
else
	polybar --reload top >> ~/.config/polybar/top.log 2>&1 &
	polybar --reload bottom >> ~/.config/polybar/bottom.log 2>&1 &
fi

