#!/bin/sh
# by gnidmoo
# Put it in ~/.local/lib/colorsrc

export WHITE="\033[0m"
export RED="\033[0;31m"
export GREEN="\033[0;32m"
export YELLOW="\033[0;33m"
export BLUE="\033[0;34m"
export MAGENTA="\033[0;35m"
export CYAN="\033[0;36m"

export BOLD="\033[1m"
export BRED="\033[1;31m"
export BGREEN="\033[1;32m"
export BYELLOW="\033[1;33m"
export BBLUE="\033[1;34m"
export BMAGENTA="\033[1;35m"
export BCYAN="\033[1;36m"

export EWHITE="\[$WHITE\]"
export ERED="\[$WRED\]"
export EGREEN="\[$GREEN\]"
export EYELLOW="\[$YELLOW\]"
export EBLUE="\[$BLUE\]"
export EMAGENTA="\[$MAGENTA\]"
export ECYAN="\[$CYAN\]"

export EBOLD="\[$BOLD\]"
export EBRED="\[$BRED\]"
export EBGREEN="\[$BGREEN\]"
export EBYELLOW="\[$BYELLOW\]"
export EBBLUE="\[$BBLUE\]"
export EBMAGENTA="\[$BMAGENTA\]"
export EBCYAN="\[$BCYAN\]"
