#!/bin/bash

if [ -z "$1" ]
then
	echo "Usage: tetrane [login|logout]"
	exit 1
fi

log_file="$HOME/.local/share/.tetrane.log"
lastline="$(tail -1 $log_file)"

if [ "$1" == "login" ]
then
	echo ""

	xrandr --output DP2 --auto --primary --right-of eDP1
	bash ~/.local/bin/update-background

	sed -i 's/eDP1/DP2/g' ~/.config/lemonbuddy/config

	if [ -z "$(echo $lastline | grep "[I]")" ]
	then
		notify-send "Logged in, welcome!"

		echo "[I]" $(date '+%a %e %b %H:%M:%S') >> $log_file
	fi

	exec ~/.config/lemonbuddy/launch
elif [ "$1" == "logout" ]
then
	echo ""

	xrandr --output eDP1 --auto --output DP2 --off

	sed -i 's/DP2/eDP1/g' ~/.config/lemonbuddy/config

	if [ -z "$(echo $lastline | grep "[O]")" ]
	then
		notify-send "Logged out, bye!"

		mpc pause

		echo "[O]" $(date '+%a %e %b %H:%M:%S') >> $log_file
	fi

	exec ~/.config/lemonbuddy/launch
fi

