#!/bin/bash

METRIC=1 #Should be 0 or 1; 0 for F, 1 for C

lyon="EUR|FR|FR069|LYON"
macon="EUR|FR|FR071|MACON"

# Check if internet is available
# ping_test="$(ping -c 1 8.8.8.8)"
# if [ -n "$(echo $ping_test | grep unreachable)" ] || [ -n "$(echo $ping_test | grep "100% packet loss")" ]
# then
# 	exit 1
# fi

if [ -z $1 ] || [ "$1" == "1" ] || [ "$1" == "4" ]
then
	locCode=$lyon
else
	locCode=$macon
fi

if [ "$locCode" == "$macon" ] && [ "$(date +%u)" -gt 5 -o "$(date +%H)" -gt 19 ]
then
	exit 0
fi

url="http://rss.accuweather.com/rss/liveweather_rss.asp?metric=${METRIC}&locCode=$locCode"

weather_info=$(curl -s "$url")

if [ -n "$weather_info" ]
then
	echo "$weather_info" | python3 ~/.i3/i3blocks/weather.py
else
	echo "   N/A"
fi

